version: "3.7"
services:
  nest-ddd-template:
    image: nest-ddd-template:latest
    build:
      context: .
      dockerfile: ./.setup/build/Dockerfile
    container_name: nest-ddd-template
    working_dir: /usr/src/app
    env_file:
      - .env.example
    environment:
      - NODE_ENV=production
    # command: [ "npm", "run", "start:debug" ]
    expose:
      - 3000
      - 9229
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/usr/src/app:rw
