version: "3.7"
services:
  confirmation-code-api:
    image: confirmation-code:latest
    build:
      context: .
      dockerfile: ./.setup/build/Dockerfile
    container_name: confirmation-code-api
    working_dir: /usr/src/app
    command: ["npm", "run", "start:debug"]
    expose:
      - 3000
      - 9229
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/usr/src/app:rw
